#!/bin/bash
scriptdir="$(dirname "$0")"
cd "$scriptdir"

echo -n "compiling test28... "

g++ -std=c++11 -pthread WordFrequencies.cpp WordFrequenciesClient.hpp \
     ../Framework/MapReduceFramework.a -o test28

echo "done"
